/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/machine.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.013']}
        position={[1.01, 1, -0.58]}
        scale={[0.26, 0.13, 0.13]}>
        <mesh
          geometry={nodes.Text009.geometry}
          material={materials['Material.012']}
          position={[-0.27, 0.01, 0.61]}
          scale={[0.96, 1.85, 1.85]}
        />
      </mesh>
      <group position={[0.74, 1.62, -0.2]} rotation={[0, 0, 0.39]} scale={[0.18, 0, 0.1]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.011']} />
      </group>
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text007.geometry}
          material={nodes.Text007.material}
          position={[1.18, -5.2, -2.6]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text008.geometry}
          material={nodes.Text008.material}
          position={[1.18, -5.2, -0.01]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text005.geometry}
          material={nodes.Text005.material}
          position={[1.12, -2.66, -5.2]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text004.geometry}
          material={nodes.Text004.material}
          position={[1.12, -2.66, -2.6]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text003.geometry}
          material={nodes.Text003.material}
          position={[1.12, -2.66, 0.04]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text002.geometry}
          material={nodes.Text002.material}
          position={[1.01, -0.02, -5.22]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[1.02, 0.03, -2.63]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[1.01, -0.02, 0]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.67, 1.7, 0.63]}
        rotation={[0, 0, 0.36]}
        scale={0.09}>
        <mesh
          geometry={nodes.Text006.geometry}
          material={nodes.Text006.material}
          position={[1.18, -5.2, -5.2]}
          rotation={[Math.PI / 2, -0.01, -Math.PI / 2]}
          scale={[2.45, 2.48, 1.68]}
        />
      </mesh>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials['Material.006']}
        position={[0.84, 1.33, -0.56]}
        rotation={[0, 0, 0.51]}
        scale={0.05}
      />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.007']} />
    </group>
  )
}

useGLTF.preload('/machine.glb')
